# Generated by Django 4.2.1 on 2023-05-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.CharField(blank=True, default='', max_length=280)),
                ('usuario', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
